[package]
name = "amdlert"
version = "4.0.1"
edition = "2024"
description = "🚨 Overheating Alerts for AMD GPUs"
authors = ["kh4f"]
license = "MIT"
repository = "https://github.com/kh4f/amdlert"
readme = "README.md"
keywords = ["amd-gpu", "temperature-monitoring", "alerts"]
categories = ["hardware-support", "command-line-utilities", "os::windows-apis"]

[[bin]]
name = "AMDlert"
path = "src/main.rs"

[dependencies]
windows = { version = "0.62", features = [
	"Win32_Foundation",
	"Win32_UI_WindowsAndMessaging",
	"Win32_Storage_FileSystem",
	"Win32_System_Pipes",
	"Win32_Security",
	"Win32_System_IO",
	"Win32_System_Registry",
	"Win32_System_Threading",
] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[build-dependencies]
cc = "1"
winresource = "0.1"
svico = "0.3"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
