name: Release

on: { push: { tags: 'v[0-9]+.[0-9]+.[0-9]+*' } }

jobs:
  release:
    runs-on: windows-latest
    permissions: { contents: write } # for creating a GitHub release
    env:
      TAG: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with: { go-version: 1.25.0 }

      - name: Set env variables
        shell: bash
        run: echo -e ZIP=${GITHUB_REPOSITORY#*/}-$TAG.zip >> $GITHUB_ENV

      - name: Build
        run: go run build.go --build

      - name: Create release archive
        run: Compress-Archive -Path HotAMD.exe -DestinationPath $env:ZIP

      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create $env:TAG $env:ZIP --title $env:TAG --draft